categories:
  - title: "⚠️  Breaking changes"
    semver-increment: "major"
    when:
      conventional:
        breaking: true
  - title: "🚀 Features"
    semver-increment: "minor"
    when:
      conventional:
        type: "feat"
  - title: "🐛 Bug Fixes"
    semver-increment: "patch"
    when:
      conventional:
        type: "fix"
  - title: "🧰 Maintenance"
    semver-increment: "patch"
    when:
      conventional:
        types: ["chore", "build", "ci", "docs", "refactor", "test"]
  - title: "📦 Other Changes"
    semver-increment: "patch"

exclude-labels:
  - duplicate
  - invalid
  - later
  - wontfix
  - kind/question
  - release/skip-changelog

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
name-template: "v$RESOLVED_VERSION"
template: |
  $CHANGES

  ## Contributors

  $CONTRIBUTORS

autolabeler:
  # Tag any PR with "!" in the subject as major update. In other words, breaking change
  - label: "kind/breaking-change"
    title:
      - "/.*!:.*/"
  - label: "area/dependencies"
    title:
      - "chore(deps)"
  - label: "area/dependencies"
    title:
      - "fix(deps)"
  - label: "area/dependencies"
    title:
      - "build(deps)"
  - label: "kind/feature"
    title:
      - "feat"
  - label: "kind/bug"
    title:
      - "fix"
  - label: "kind/chore"
    title:
      - "chore"
