name: Sign image

on:
  workflow_call:
    inputs:
      image-digest:
        type: string
        required: true

jobs:
  sign:
    name: Sign image
    permissions:
      packages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign container image
        run: |
          cosign sign --yes \
            ghcr.io/${{github.repository_owner}}/kubewarden-controller@${{ inputs.image-digest }}

          cosign verify \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --certificate-identity-regexp="https://github.com/${{github.repository_owner}}/kubewarden-controller/.github/workflows/sign-image.yml@${{ github.ref }}" \
            ghcr.io/${{github.repository_owner}}/kubewarden-controller@${{ inputs.image-digest }}
